# Generated by Django 4.2.7 on 2023-12-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modeloImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cBuyLogo', models.ImageField(upload_to='Assets/')),
            ],
        ),
    ]
