# Generated by Django 4.2.7 on 2023-12-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeloimagenes',
            old_name='cBuyLogo',
            new_name='imagenes',
        ),
    ]
