# Generated by Django 4.2.7 on 2023-12-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_user_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
