# Generated by Django 4.2.7 on 2023-12-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuariocustom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioCustom',
        ),
    ]
